import {useEffect,useState} from "react";
import {useApp} from "../state";
import {setSetting} from "../lib/api";
import {readSecret,removeSecret,secretPresence,storeSecret} from "../lib/keys";
import {webConfig,type WebConfig} from "../agent/web";
export function WebSettings(){const ru=useApp().locale==="ru";const [config,setConfig]=useState<WebConfig>({enabled:false,allow:[],deny:[]}),[key,setKey]=useState(""),[present,setPresent]=useState(false),[error,setError]=useState(""),[saved,setSaved]=useState(false),[allowText,setAllowText]=useState(""),[denyText,setDenyText]=useState("");useEffect(()=>{webConfig().then(c=>{setConfig(c);setAllowText(c.allow.join(", "));setDenyText(c.deny.join(", "));}).catch(e=>setError(String(e)));/* presence flag, no Keychain read; keys saved before flags existed are read once here */secretPresence("web:brave").then(p=>p??readSecret("web:brave").then(k=>!!k)).then(setPresent).catch(()=>{});},[]);
 const domains=(s:string)=>s.split(/[\s,]+/).map(d=>d.toLowerCase().replace(/^https?:\/\//,"").replace(/\/$/,"")).filter(Boolean);
 return <><h4>{ru?"Интернет для API-моделей":"Web tools for API models"}</h4><p className="lead">{ru?"Поиск через Brave Search API; чтение публичных HTTPS-страниц. Запрос поиска передаётся Brave. В режиме Авто каждое действие требует разрешения. CLI используют свои инструменты.":"Brave Search API and public HTTPS pages. Search queries are sent to Brave. Auto mode asks before each action. CLI providers use their own tools."}</p><label><input type="checkbox" checked={config.enabled} onChange={e=>{setConfig({...config,enabled:e.target.checked});setSaved(false);}}/>{ru?"Разрешить веб-инструменты":"Enable web tools"}</label>
 <label>Brave API key{present?" ✓":""}<input type="password" className="input" autoComplete="off" value={key} placeholder={present?"••••••••":""} onChange={e=>{setKey(e.target.value);setSaved(false);}}/></label>
 <label>{ru?"Разрешённые домены (пусто — все публичные)":"Allowed domains (empty = all public)"}<input className="input" value={allowText} onChange={e=>{setAllowText(e.target.value);setSaved(false);}}/></label>
 <label>{ru?"Запрещённые домены":"Denied domains"}<input className="input" value={denyText} onChange={e=>{setDenyText(e.target.value);setSaved(false);}}/></label>
 <button className="btn-soft" onClick={async()=>{try{if(key.trim()){await storeSecret("web:brave",key.trim());setPresent(true);setKey("");}const next={...config,allow:domains(allowText),deny:domains(denyText)};await setSetting("webTools",next);setConfig(next);setSaved(true);setError("");}catch(e){setError(String(e));}}}>{ru?"Сохранить":"Save"}</button>{saved&&<span role="status">{ru?"Сохранено":"Saved"}</span>}{present&&<button className="btn-ghost" onClick={async()=>{try{await removeSecret("web:brave");setPresent(false);}catch(e){setError(String(e));}}}>{ru?"Удалить ключ":"Remove key"}</button>}{error&&<div role="alert">{error}</div>}</>;
}
